### PR TITLE
"Essential compatibility" but prefere the term "send texture on full boot of the game"

### PR DESCRIPTION
**Pull request by craftish37**
This PR talks for itself, it's where the war is starting to make cosmetics textures sent earlier in the game launching, to avoid this kind of mess with Essential players :
image
image
image

Also check why the cape isn't rendering on the doll but more Essential stuff I think

### CODE REVIEW

**Comment by craftish37** [comment]
After deep looking (approximatively 5 minutes) I can affirm that I'm not competent enough to ensure this task, blaming me is authorized 👌

**Comment by craftish37** [comment]
Just thought about it, but essential compatibility is actually a thing to do 'cause they are also purposing cosmetics 👀

**Comment by craftish37** [comment]
Dead PR ? No !
I search everywhere for ways to make this puppet works, but the only thing I can do is hopping it updates when I join a server and come back to the menu xd

I
am
bad

**Comment by valoeghese** [comment]
Found the source of this issue while developing a new menu and running into the same problem. 🥴

**Comment by craftish37** [comment]
WhY DiDn’T YoU AcCePt ThE LoLiFiCaTiOn ?!?!?! 😱😱🥴

**Pull request closed without merging**
